stages:
    - validate
    - plan
    - apply
    - upload
    - destroy

image:
  name: hashicorp/terraform:$TF_VERSION
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
    TF_VERSION: 1.9.2
    TF_WORKING_DIR: terraform ## Specify the directory containing your Terraform scripts
    TF_VAR_aws_region: ${AWS_DEFAULT_REGION}
    TF_VAR_aws_access_key: ${AWS_ACCESS_KEY_ID}
    TF_VAR_aws_secret_key: ${AWS_SECRET_ACCESS_KEY}
    AWS_BUCKET_NAME: element-simulation-3107

before_script:
    - terraform --version
    - cd $TF_WORKING_DIR
    - terraform init

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    script:
        - terraform plan -out=tfplan
    artifacts:
        paths:
            - $TF_WORKING_DIR/tfplan

apply:
    stage: apply
    script:
        - terraform apply -auto-approve tfplan
    artifacts:
        paths:
            - $TF_WORKING_DIR/terraform.tfstate
            - $TF_WORKING_DIR/terraform.tfstate.backup
    when: manual

deploy to s3:
    stage: upload
    image: 
        name: amazon/aws-cli:2.17.11
        entrypoint: [""]
    before_script: []
    script:
        - aws --version
        - aws s3 sync build/ s3://$AWS_BUCKET_NAME/
    needs:
        - apply

destroy:
    stage: destroy
    script:
        - terraform destroy -auto-approve
    when: manual
